# Generated by Django 5.2.1 on 2025-09-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_maker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupcreationmodel",
            name="members_string",
            field=models.TextField(
                default="",
                help_text='Comma-separated list of names. (f.e.: "Toki, Tina, Alice") |\n Avoid using the same name for different members',
            ),
        ),
    ]
