# Generated by Django 5.2.1 on 2026-01-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_maker', '0002_alter_groupcreationmodel_members_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcreationmodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
