# Generated by Django 5.2.1 on 2026-02-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_maker', '0003_alter_groupcreationmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcreationmodel',
            name='members_string',
            field=models.TextField(default='', help_text='Comma-separated names. (f.e.: "Toki, Tina, Alice") | We recommend not using the same exact name for different members'),
        ),
    ]
