# Generated by Django 5.2.1 on 2026-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_maker', '0004_alter_groupcreationmodel_members_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcreationmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
