# Generated by Django 5.2.13 on 2026-05-04 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Bug report'), ('question', 'Question'), ('feature', 'Feature request')], default='bug', max_length=16)),
                ('subject', models.CharField(max_length=140)),
                ('body', models.TextField(max_length=5000)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('page_url', models.CharField(blank=True, max_length=512)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
