# Generated by Django 5.2.1 on 2026-02-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
