# Generated by Django 5.2.15 on 2026-10-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_member_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
