# Generated by Django 5.2.1 on 2026-04-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='saved_count',
            field=models.IntegerField(default=0),
        ),
    ]
