# Generated by Django 5.2.1 on 2026-04-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzmaker', '0002_quiz_saved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='expected_duration',
            field=models.IntegerField(default=0, help_text='Expected duration in minutes'),
        ),
    ]
