# Generated by Django 5.2.1 on 2026-04-25 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzmaker', '0003_quiz_expected_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quizzmaker/rounds/'),
        ),
        migrations.AddField(
            model_name='round',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='question_type',
            field=models.CharField(choices=[('select_correct', 'Select correct answer'), ('type_input', 'Type input field')], default='select_correct', max_length=20),
        ),
        migrations.AddField(
            model_name='round',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Time limit in seconds (0 = no limit)'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzmaker.round')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
