# Generated by Django 5.2.1 on 2026-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzmaker', '0004_round_image_round_points_round_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='question_type',
            field=models.CharField(choices=[('select_correct', 'Select correct answer'), ('type_input', 'Type input field'), ('drag_answer', 'Drag to the correct blank spot')], default='select_correct', max_length=20),
        ),
    ]
