# Generated by Django 5.2.1 on 2026-04-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzmaker', '0005_alter_round_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='question',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
