# Generated by Django 5.2.1 on 2026-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzmaker', '0009_focus_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='expected_duration',
            field=models.IntegerField(default=1, help_text='Expected duration in minutes'),
        ),
    ]
