# Generated by Django 5.2.1 on 2026-04-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzmaker', '0010_alter_quiz_expected_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='title',
        ),
    ]
