# Generated by Django 5.2.1 on 2025-09-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="member",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
