# Generated by Django 5.2.1 on 2025-09-01 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_maker", "0002_alter_groupcreationmodel_members_string"),
        ("point_system", "0002_alter_member_options_member_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="total",
            new_name="negative_total",
        ),
        migrations.AddField(
            model_name="member",
            name="positive_total",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "field_type",
                    models.CharField(
                        choices=[("int", "numerical"), ("str", "text")], max_length=10
                    ),
                ),
                (
                    "polarity",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        default="positive",
                        max_length=10,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="group_maker.groupcreationmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "name")},
            },
        ),
    ]
