# Generated by Django 5.2.1 on 2025-09-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_maker", "0002_alter_groupcreationmodel_members_string"),
        ("point_system", "0003_rename_total_member_negative_total_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="data",
            new_name="negative_data",
        ),
        migrations.AddField(
            model_name="member",
            name="positive_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="member",
            name="negative_total",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="member",
            name="positive_total",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative")],
                        default="positive",
                        max_length=10,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="group_maker.groupcreationmodel",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "name")},
            },
        ),
        migrations.DeleteModel(
            name="Column",
        ),
    ]
