# Generated by Django 5.2.1 on 2025-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point_system", "0004_rename_data_member_negative_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddefinition",
            name="definition",
            field=models.CharField(
                choices=[("positive", "Positive"), ("negative", "Negative")],
                default="positive",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="type",
            field=models.CharField(
                choices=[("int", "Numerical"), ("str", "Text")],
                default="positive",
                max_length=10,
            ),
        ),
    ]
