# Generated by Django 5.2.1 on 2025-09-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("group_maker", "0002_alter_groupcreationmodel_members_string"),
        ("point_system", "0005_fielddefinition_definition_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fielddefinition",
            unique_together={("group", "name", "definition")},
        ),
    ]
