# Generated by Django 5.2.1 on 2025-09-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("point_system", "0006_alter_fielddefinition_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["id"]},
        ),
        migrations.AlterUniqueTogether(
            name="fielddefinition",
            unique_together=set(),
        ),
    ]
