# Generated by Django 5.2.1 on 2025-09-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("point_system", "0007_alter_member_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={},
        ),
    ]
