# Generated by Django 5.2.1 on 2025-09-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("point_system", "0008_alter_member_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["name"]},
        ),
    ]
