# Generated by Django 5.2.1 on 2025-09-03 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point_system", "0009_alter_member_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="fielddefinition",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2025, 9, 3, 8, 25, 34, 444399, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fielddefinition",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
