# Generated by Django 5.2.1 on 2025-09-03 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "point_system",
            "0010_alter_member_options_fielddefinition_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="fielddefinition",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
