# Generated by Django 5.2.1 on 2025-09-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_maker", "0002_alter_groupcreationmodel_members_string"),
        ("point_system", "0011_member_created_at_member_updated_at_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fielddefinition",
            constraint=models.UniqueConstraint(
                fields=("group", "name", "definition"),
                name="unique_field_per_group_and_table",
            ),
        ),
    ]
