# Generated by Django 5.2.1 on 2026-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_system', '0012_fielddefinition_unique_field_per_group_and_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='type',
            field=models.CharField(choices=[('int', 'Numerical'), ('str', 'Text')], default='int', max_length=10),
        ),
    ]
