# Generated by Django 5.2.15 on 2026-06-23 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group_maker", "0005_alter_groupcreationmodel_title"),
        ("point_system", "0015_fielddefinition_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointSystemGroupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_positive", models.BooleanField(default=True)),
                ("show_negative", models.BooleanField(default=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_settings",
                        to="group_maker.groupcreationmodel",
                    ),
                ),
            ],
        ),
    ]
