# Generated by Django 5.2.1 on 2026-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('pastel', 'Pastel')], default='light', max_length=10),
        ),
    ]
