# Generated by Django 5.2.1 on 2026-01-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calculator_uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='divider_uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wheel_spins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
