# Generated by Django 5.2.1 on 2026-02-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_calculator_uses_customuser_divider_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Português'), ('cs', 'Čeština')], default='en', max_length=10),
        ),
    ]
