# Generated by Django 5.2.1 on 2026-02-17 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_language_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='calculator_uses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='divider_uses',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wheel_spins',
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_uses', models.PositiveIntegerField(default=0)),
                ('wheel_spins', models.PositiveIntegerField(default=0)),
                ('divider_uses', models.PositiveIntegerField(default=0)),
                ('stopwatch_starts', models.PositiveIntegerField(default=0)),
                ('stopwatch_flags', models.PositiveIntegerField(default=0)),
                ('stopwatch_total_ms', models.PositiveBigIntegerField(default=0)),
                ('countdown_starts', models.PositiveIntegerField(default=0)),
                ('countdown_total_ms', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User stats',
            },
        ),
    ]
