# Generated by Django 5.2.1 on 2026-04-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_calculator_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('pastel', 'Pastel'), ('lemonade', 'Editorial'), ('fantasy', 'Palette')], default='light', max_length=10),
        ),
    ]
