# Generated by Django 5.2.13 on 2026-05-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('CZ', 'Czech Republic'), ('PT', 'Portugal'), ('EN', 'England')], default='', max_length=2),
        ),
    ]
