# Generated by Django 5.2.15 on 2026-06-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_terms_accepted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("pastel", "Pastel"),
                    ("lemonade", "Editorial"),
                    ("fantasy", "Palette"),
                ],
                default="fantasy",
                max_length=10,
            ),
        ),
    ]
